### ISSUE TITLE
 git submodule update fails with WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

### ISSUE THREAD

**Issue by rogermc2** [simonjwright/FreeRTOS-Ada#46]
mac silicon osx sonoma

sudo  git submodule update
Cloning into '/System/Volumes/Data/Ada_Source/FreeRTOS-Ada/FreeRTOS-Kernel'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /var/root/.ssh/known_hosts to get rid of this message.
Offending RSA key in /var/root/.ssh/known_hosts:1
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

**Comment by simonjwright** [comment]
[This](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints) is the related Github doc, which seems to match at a first glance.

Thanks for the info, though I don’t have the problem, and there’s nothing I could to about it anyway.

[This blog entry](https://github.blog/news-insights/company-news/we-updated-our-rsa-ssh-host-key/#:~:text=Add%20correct%20host%20key%20in%20~%2F.ssh%2Fknown_hosts%20to%20get,remove%20the%20old%20key%20by%20running%20this%20command%3A) (dated March 2023???) says how to deal with it. My `known_hosts` file matches the value stated there (I only check the beginning and end, sorry)
